### ISSUE TITLE
Chrome shows no text when started by chromedriver

### ISSUE THREAD

**Issue by nicodh** [karma-runner/karma-chrome-launcher#183] opened 2018-06-29 20:10 UTC
If I run tests in an angular-cli project via karma with chromedriver 2.40 chrome shows no text at all.
The tests are successful, even if I check for HTML text values, but nothing is readable.
<img width="1194" alt="bildschirmfoto 2018-06-29 um 22 01 44" src="https://user-images.githubusercontent.com/1428457/42112427-0ef361ee-7be8-11e8-9606-085d845552ed.png">

Even the dev tools (here opened in the right bar) and any other website I open have no text rendered.
When running the end2end Tests with protractor I had the same problem which I could fix by adding the flag --no-sandbox. In Karma that didn't help.

If I open another Chrome instance manually everything works as expected.

<img width="1338" alt="bildschirmfoto 2018-06-29 um 21 57 51" src="https://user-images.githubusercontent.com/1428457/42112317-b4fbe4fe-7be7-11e8-9d60-6909e46ed107.png">

I'm on MacOSX  Sierra 10.12.6. Chrome Version is 67.0.3396.99 (Offizieller Build) (64-Bit)
My karma config is:
`

    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false

`

**Comment by edwinm** [comment] 2018-07-02 14:19
I had the same problem and found a fix: add the `--disable-gpu` flag.

`
config.set({
...
    browsers: ['ChromeNoGpu'],
...
    },
    customLaunchers: {
      ChromeNoGpu: {
        base: 'Chrome',
        flags: ['--disable-gpu']
      }
    }
  });
`

**Comment by nicodh** [comment] 2018-07-02 16:09
Your fix works for me too! Thanks!
But I think the issue should be kept, since it should work without setting this flag I assume...

**Comment by vfreefly** [comment] 2018-07-10 16:08
I found 2.40 chromedriver version is pretty baggy, don't recommend it, use 2.39 for now

**Comment by Itrulia** [comment] 2018-07-10 19:41
Only happens on a mac

**Comment by rogeriopvl** [comment] 2018-12-07 16:12
Issue seems to be fixed in recent versions.

Failed to reproduce the problem with a vanilla angular-cli project:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/38240/49658681-8b7be580-fa3a-11e8-9b7c-747c55d5543e.png">

**Closed by rogeriopvl** 2018-12-07 16:12 UTC
Labels: needs: investigation
