### ISSUE TITLE
No README data

### ISSUE THREAD

**Issue by nottinhill** [karma-runner/karma-chrome-launcher#43] opened 2015-04-09 09:36 UTC
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

**Comment by Krinkle** [comment] 2015-04-16 04:02
Duplicate of #40.

**Comment by zzo** [comment] 2015-04-16 17:33
fixed

**Comment by nottinhill** [comment] 2015-04-16 17:33
Cool, 1 down, 15 to go (dependencies in my project who forgot the README)

Am 16.04.2015 um 19:33 schrieb Mark Trostler:

**Closed by zzo** 2015-04-16 17:33 UTC
